#pragma once
#include "i18n.h"

static const char* const msgs_de[MSG_COUNT] = {
    [MSG_TYPE_HELP_FOR_COMMANDS] = "Tippe 'help' für eine Liste der Befehle.",
    [MSG_CALCULATING_MOON]       = "Berechne Mondposition...",
    [MSG_DONE]                   = "Fertig.",
    [MSG_STARTING_DYNAMIC_MOON]  = "Starte dynamische Mondanzeige...",
    [MSG_UPDATING_MOON]          = "Aktualisiere Mondanzeige...",
    [MSG_TIME_UPDATED]           = "Zeit aktualisiert.",
    [MSG_WIFI_CONNECTIONS]       = "Aktuelle WLAN-Verbindungen:",
    [MSG_WIFI_ENABLING]          = "WLAN-Verbindung aktivieren...",
    [MSG_WIFI_DISABLING]         = "WLAN-Verbindung trennen...",
    [MSG_CONFIG_HEADER]          = "Aktuelle Konfiguration:",
    [MSG_LANGUAGE_LINE]          = "  Sprache:     deutsch\n",
    [MSG_LANGUAGE_SET]           = "Sprache gesetzt: deutsch",
    [MSG_POLAR_DAY_NIGHT]        = "  Sonnenauf/-untergang: Polartag oder Polarnacht.",
    [MSG_EXPECTED_TIME_FORMAT]   = "Erwartet: HH:MM:SS oder TT.MM.JJJJ HH:MM:SS",
    [MSG_CONFIG_TIME_UNAVAILABLE]   = "  Zeit:        (nicht verfügbar)",
    [MSG_CONFIG_WIFI_DISABLED]      = "  WLAN:        deaktiviert",
    [MSG_CONFIG_WIFI_DISCONNECTED]  = "  WLAN:        nicht verbunden",
    [MSG_NTP_UNKNOWN]               = "unbekannt",
    [MSG_NTP_NOT_SYNCED]            = "nicht synchronisiert",
    [MSG_NTP_SYNCED]                = "synchronisiert",
    [MSG_NTP_SYNCING]               = "wird synchronisiert",

    [FMT_UNRECOGNIZED_CMD]       = "Unbekannter Befehl [%s]\n",
    [FMT_LOCATION_SAVED]         = "Standort gespeichert: %.6f / %.6f\n",
    [FMT_OPTIONS_SAVED]          = "Anzeigeoptionen gespeichert: %d\n",
    [FMT_CONFIG_LATITUDE]        = "  Breitengrad: %.6f\n",
    [FMT_CONFIG_LONGITUDE]       = "  Längengrad:  %.6f\n",
    [FMT_CONFIG_OPTIONS]         = "  Optionen:    %d (0x%X)\n",
    [FMT_CONFIG_OPT_DARKEN]      = "    [%c] darken_unlit    (1)\n",
    [FMT_CONFIG_OPT_BLUISH]      = "    [%c] bluish_tint     (2)\n",
    [FMT_CONFIG_OPT_NASA]        = "    [%c] use_nasa_model  (4)\n",
    [FMT_CONFIG_OPT_LIBRATION]   = "    [%c] use_libration   (8)\n",
    [FMT_CONFIG_TIME]            = "  Zeit:        %s\n",
    [FMT_CONFIG_NTP]             = "  NTP:         %s (%s)\n",
    [FMT_CONFIG_WIFI_CONNECTED]  = "  WLAN:        verbunden mit %s (%d dBm, IP %s)\n",

    [ERR_INVALID_FORMAT_LABEL]      = "Ungültiges Format:",
    [ERR_NO_NTP_TIME]               = "Keine gültige NTP-Zeit verfügbar.",
    [ERR_INVALID_DATETIME_FORMAT]   = "Ungültiges Format. Erwartet: TT.MM.JJJJ HH:MM:SS",
    [ERR_INVALID_WIFI_ARG]          = "Ungültiges Argument. Erwartet: on oder off",
    [ERR_INVALID_LOCATION_FORMAT]   = "Ungültiges Format. Erwartet: set_location <lat> <lon>",
    [ERR_INVALID_COORDINATES]       = "Ungültige Werte. Lat: -90..90, Lon: -180..180",
    [ERR_INVALID_OPTIONS_FORMAT]    = "Ungültiges Format. Erwartet: set_options <wert>",
    [ERR_INVALID_OPTIONS_VALUE]     = "Ungültiger Wert für Optionen.",
    [ERR_INVALID_LANG]              = "Ungültige Sprache. Erwartet: de oder en-us",
    [ERR_NO_NTP_SUN]                = "Keine gültige NTP-Zeit für Sonnenberechnung.",

    [HELP_HEADER]        = "Verfügbare Befehle:",
    [HELP_HELP]          = "  help - Diese Hilfe anzeigen",
    [HELP_MOON]          = "  moon [HH:MM:SS | TT.MM.JJJJ HH:MM:SS] - Mondphase für angegebene Zeit anzeigen (oder aktuelle Zeit ohne Argument)",
    [HELP_MOON_RUN]      = "  moon_run - Dynamische Mondanzeige starten (Aktualisierung jede Minute)",
    [HELP_WIFI]          = "  wifi [on|off] - WLAN ein- oder ausschalten",
    [HELP_SET_TIME]      = "  set_time TT.MM.JJJJ HH:MM:SS - Systemzeit setzen (UTC)",
    [HELP_SET_LOCATION]  = "  set_location <lat> <lon> - Standort persistent speichern (Dezimalgrad)",
    [HELP_SET_OPTIONS]   = "  set_options <wert> - Anzeigeoptionen persistent speichern (Bitfeld)",
    [HELP_OPTIONS_BITS]  = "    Bits: 1=darken_unlit, 2=bluish_tint, 4=use_nasa_model, 8=use_libration",
    [HELP_CONFIG]        = "  config - Aktuelle Konfiguration anzeigen",
    [HELP_SET_LANG]      = "  set_lang <de|en-us> - Ausgabesprache umschalten",

    [DBG_JULIAN_DATE]       = "  Julianisches Datum:       %f\n",
    [DBG_MOON_RADEC]        = "  Mondposition RA/Dek:      %6.2f° / %6.2f°\n",
    [DBG_MOON_AZALT]        = "  Mondposition Azimut/Höhe: %6.2f° / %6.2f°\n",
    [DBG_MOON_LIBRATION]    = "  Mondlibration:            %6.2f° / %6.2f°\n",
    [DBG_MOON_AXLE]         = "  Mondachse:                %6.2f°\n",
    [DBG_MOON_PHASE]        = "  Mondphase (0-1):          %6.4f\n",
    [DBG_MOON_LIMB]         = "  Mondrand:                 %6.2f°\n",
    [DBG_PARALLACTIC_ANGLE] = "  Parallaktischer Winkel:   %6.2f°\n",
    [DBG_SIDEREAL_TIME]     = "  Sternzeit:                %6.2f°\n",
    [DBG_TIMING_TOTAL]      = "  ── Gesamt: %lu µs\n",

    [HHMM_SUNRISE] = "Sonnenaufgang:",
    [HHMM_SUNSET]  = "Sonnenuntergang:",
};
