#pragma once
#include "i18n.h"

static const char* const msgs_en_us[MSG_COUNT] = {
    [MSG_TYPE_HELP_FOR_COMMANDS] = "Type 'help' for a list of commands.",
    [MSG_CALCULATING_MOON]       = "Calculating moon position...",
    [MSG_DONE]                   = "Done.",
    [MSG_STARTING_DYNAMIC_MOON]  = "Starting dynamic moon display...",
    [MSG_UPDATING_MOON]          = "Updating moon display...",
    [MSG_TIME_UPDATED]           = "Time updated.",
    [MSG_WIFI_CONNECTIONS]       = "Current WiFi connections:",
    [MSG_WIFI_ENABLING]          = "Enabling WiFi connection...",
    [MSG_WIFI_DISABLING]         = "Disconnecting WiFi...",
    [MSG_CONFIG_HEADER]          = "Current configuration:",
    [MSG_LANGUAGE_LINE]          = "  Language:    english\n",
    [MSG_LANGUAGE_SET]           = "Language set: english",
    [MSG_POLAR_DAY_NIGHT]        = "  Sunrise/sunset: polar day or polar night.",
    [MSG_EXPECTED_TIME_FORMAT]   = "Expected: HH:MM:SS or DD.MM.YYYY HH:MM:SS",
    [MSG_CONFIG_TIME_UNAVAILABLE]   = "  Time:        (not available)",
    [MSG_CONFIG_WIFI_DISABLED]      = "  WiFi:        disabled",
    [MSG_CONFIG_WIFI_DISCONNECTED]  = "  WiFi:        not connected",
    [MSG_NTP_UNKNOWN]               = "unknown",
    [MSG_NTP_NOT_SYNCED]            = "not synchronized",
    [MSG_NTP_SYNCED]                = "synchronized",
    [MSG_NTP_SYNCING]               = "synchronizing",

    [FMT_UNRECOGNIZED_CMD]       = "Unrecognized command [%s]\n",
    [FMT_LOCATION_SAVED]         = "Location saved: %.6f / %.6f\n",
    [FMT_OPTIONS_SAVED]          = "Display options saved: %d\n",
    [FMT_CONFIG_LATITUDE]        = "  Latitude:    %.6f\n",
    [FMT_CONFIG_LONGITUDE]       = "  Longitude:   %.6f\n",
    [FMT_CONFIG_OPTIONS]         = "  Options:     %d (0x%X)\n",
    [FMT_CONFIG_OPT_DARKEN]      = "    [%c] darken_unlit    (1)\n",
    [FMT_CONFIG_OPT_BLUISH]      = "    [%c] bluish_tint     (2)\n",
    [FMT_CONFIG_OPT_NASA]        = "    [%c] use_nasa_model  (4)\n",
    [FMT_CONFIG_OPT_LIBRATION]   = "    [%c] use_libration   (8)\n",
    [FMT_CONFIG_TIME]            = "  Time:        %s\n",
    [FMT_CONFIG_NTP]             = "  NTP:         %s (%s)\n",
    [FMT_CONFIG_WIFI_CONNECTED]  = "  WiFi:        connected to %s (%d dBm, IP %s)\n",

    [ERR_INVALID_FORMAT_LABEL]      = "Invalid format:",
    [ERR_NO_NTP_TIME]               = "No valid NTP time available.",
    [ERR_INVALID_DATETIME_FORMAT]   = "Invalid format. Expected: DD.MM.YYYY HH:MM:SS",
    [ERR_INVALID_WIFI_ARG]          = "Invalid argument. Expected: on or off",
    [ERR_INVALID_LOCATION_FORMAT]   = "Invalid format. Expected: set_location <lat> <lon>",
    [ERR_INVALID_COORDINATES]       = "Invalid values. Lat: -90..90, Lon: -180..180",
    [ERR_INVALID_OPTIONS_FORMAT]    = "Invalid format. Expected: set_options <value>",
    [ERR_INVALID_OPTIONS_VALUE]     = "Invalid value for options.",
    [ERR_INVALID_LANG]              = "Invalid language. Expected: de or en-us",
    [ERR_NO_NTP_SUN]                = "No valid NTP time for sun calculation.",

    [HELP_HEADER]        = "Available commands:",
    [HELP_HELP]          = "  help - Show this help message",
    [HELP_MOON]          = "  moon [HH:MM:SS | DD.MM.YYYY HH:MM:SS] - Display moon phase for given time (or current time if no argument)",
    [HELP_MOON_RUN]      = "  moon_run - Start dynamic moon display (updates every minute)",
    [HELP_WIFI]          = "  wifi [on|off] - Turn WiFi on or off",
    [HELP_SET_TIME]      = "  set_time DD.MM.YYYY HH:MM:SS - Set system time (UTC)",
    [HELP_SET_LOCATION]  = "  set_location <lat> <lon> - Save location persistently (decimal degrees)",
    [HELP_SET_OPTIONS]   = "  set_options <value> - Save display options persistently (bitfield)",
    [HELP_OPTIONS_BITS]  = "    Bits: 1=darken_unlit, 2=bluish_tint, 4=use_nasa_model, 8=use_libration",
    [HELP_CONFIG]        = "  config - Show current configuration",
    [HELP_SET_LANG]      = "  set_lang <de|en-us> - Switch output language",

    [DBG_JULIAN_DATE]       = "  Julian date:              %f\n",
    [DBG_MOON_RADEC]        = "  Moon position RA/Dec:     %6.2f° / %6.2f°\n",
    [DBG_MOON_AZALT]        = "  Moon position Az/Alt:     %6.2f° / %6.2f°\n",
    [DBG_MOON_LIBRATION]    = "  Moon libration:           %6.2f° / %6.2f°\n",
    [DBG_MOON_AXLE]         = "  Moon axis:                %6.2f°\n",
    [DBG_MOON_PHASE]        = "  Moon phase (0-1):         %6.4f\n",
    [DBG_MOON_LIMB]         = "  Moon limb angle:          %6.2f°\n",
    [DBG_PARALLACTIC_ANGLE] = "  Parallactic angle:        %6.2f°\n",
    [DBG_SIDEREAL_TIME]     = "  Sidereal time:            %6.2f°\n",
    [DBG_TIMING_TOTAL]      = "  ── Total: %lu µs\n",

    [HHMM_SUNRISE] = "Sunrise:",
    [HHMM_SUNSET]  = "Sunset:",
};
